yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, PasswordChangeDoneView,
    PasswordChangeView, PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path


from . import views

app_name = 'users'

urlpatterns = [
    # Регистрация (шаблон из Django)
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout',
    ),
    #
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    # Изменение пароля
    path(
        'password_change/',
        PasswordChangeView.as_view(),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    # Восстановление пароля
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uid64>/<token>/',
        PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    # Django проверяет url-адреса сверху вниз,
    # нам нужно, чтобы Django сначала проверял адреса в приложении users
    path('auth/', include('users.urls', namespace='users')),
    # Если какой-то URL не обнаружится в приложении users —
    # Django пойдёт искать его в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403csrf = 'core.views.csrf_failure'
handler403 = 'core.views.permission_denied'

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>
    © {{ year }} Copyright <span style="color:red">Ya</span>tube
  </p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="/">
        <img src="{% static 'img/logo.png' %}"
             width="30"
             height="30"
             class="d-inline-block align-top"
             alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов
      {% endcomment %}
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
               href="{% url 'about:author' %}">
              Об авторе
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
               href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
                 href="{% url 'posts:post_create' %}">
                Новая запись
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}"
                 href="{% url 'users:password_change_form' %}">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}"
                 href="{% url 'users:logout' %}">
                Выйти
              </a>
            </li>
            <li>
              Пользователь: {{ user.username }}
              <li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
                     href="{% url 'users:login' %}">
                    Войти
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
                     href="{% url 'users:signup' %}">
                    Регистрация
                  </a>
                </li>
              {% endif %}
            {% endwith %}
          </ul>
        </div>
      </nav>
    </header>